# Generated by Django 3.0.5 on 2021-01-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210105_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiddetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
