# Generated by Django 3.0.5 on 2020-11-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_password_reset_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password_reset_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
