# Generated by Django 3.0.5 on 2020-12-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_password_reset_confirmed',
        ),
    ]
