# Generated by Django 3.0.5 on 2021-01-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rfiddetail_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfiddetail',
            old_name='active',
            new_name='is_assigned',
        ),
    ]
