# Generated by Django 3.0.5 on 2021-01-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210105_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiddetail',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
