# Generated by Django 3.0.5 on 2020-12-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payheredetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payheredetails',
            name='custom_1',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='custom_2',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='md5sig',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='payhere_currency',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='payheredetails',
            name='status_message',
        ),
    ]
