# Generated by Django 3.0.5 on 2021-01-05 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210105_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='rf_id',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='RequestPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('expire_on', models.DateTimeField(default=datetime.datetime(2021, 1, 5, 16, 26, 52, 791473))),
                ('rf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RFID')),
            ],
        ),
    ]
