# Generated by Django 3.0.5 on 2020-12-02 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201202_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='payheredetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
