# Generated by Django 3.0.5 on 2021-01-05 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210105_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestpool',
            old_name='rf_id',
            new_name='rfid',
        ),
        migrations.AlterField(
            model_name='requestpool',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 16, 36, 22, 512590)),
        ),
    ]
