# Generated by Django 3.0.5 on 2021-01-05 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210105_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpool',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 16, 37, 22, 756761)),
        ),
    ]
