# Generated by Django 3.0.5 on 2021-01-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210105_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpool',
            name='expire_on',
        ),
    ]
