# Generated by Django 3.0.5 on 2021-01-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210106_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpool',
            name='is_active',
        ),
    ]
